import streamlit as st
import pandas as pd
import geopandas as gpd


@st.cache_data
def load_data():
    census = pd.read_csv("data/raw/erie_tract_data.csv")
    census["tract_code"] = census["tract_code"].astype(str).str.zfill(6)
    sh_data = pd.read_csv("data/raw/erie_food_insecurity.csv")
    sh_data["tract_code"] = sh_data["tract_code"].astype(str).str.zfill(6)
    pantries = pd.read_csv("data/raw/ErieCountyFoodPantries.csv")
    benchmarks_national = pd.read_csv("data/raw/benchmarks_national.csv")
    benchmarks_pa = pd.read_csv("data/raw/benchmarks_pennsylvania.csv")
    benchmarks_erie = pd.read_csv("data/raw/benchmarks_erie.csv")
    benchmarks_counties = pd.read_csv("data/raw/benchmarks_pa_counties.csv")
    transit_stats = pd.read_csv("data/processed/tract_transit_stats.csv")
    transit_stats["TRACTCE"] = transit_stats["TRACTCE"].astype(str).str.zfill(6)
    zcta_data = pd.read_csv("data/raw/zcta_data.csv")
    zcta_data["zcta"] = zcta_data["zcta"].astype(str).str.zfill(5)
    cdc_places = pd.read_csv("data/raw/cdc_places_tract.csv", dtype={"tract_code": str})
    cdc_places["tract_code"] = cdc_places["tract_code"].str.zfill(6)
    food_atlas = pd.read_csv("data/raw/usda_food_atlas.csv", dtype={"tract_code": str})
    food_atlas["tract_code"] = food_atlas["tract_code"].str.zfill(6)
    demographics = pd.read_csv("data/raw/tract_demographics.csv", dtype={"tract_code": str})
    demographics["tract_code"] = demographics["tract_code"].str.zfill(6)

    # ZIP-level CDC PLACES health data (generated by fetch_cdc_places_zcta.py)
    cdc_places_zcta_path = "data/raw/cdc_places_zcta.csv"
    if pd.io.common.file_exists(cdc_places_zcta_path):
        cdc_places_zcta = pd.read_csv(cdc_places_zcta_path, dtype={"zcta": str})
        cdc_places_zcta["zcta"] = cdc_places_zcta["zcta"].str.zfill(5)
    else:
        cdc_places_zcta = pd.DataFrame(columns=["zcta"])

    # ZIP-level POI counts and nearest distances (generated by generate_zcta_poi_stats.py)
    zcta_poi_path = "data/processed/zcta_poi_stats.csv"
    if pd.io.common.file_exists(zcta_poi_path):
        zcta_poi_stats = pd.read_csv(zcta_poi_path, dtype={"ZCTA5CE20": str})
        zcta_poi_stats["ZCTA5CE20"] = zcta_poi_stats["ZCTA5CE20"].str.zfill(5)
    else:
        zcta_poi_stats = pd.DataFrame(columns=["ZCTA5CE20"])

    return (census, sh_data, pantries,
            benchmarks_national, benchmarks_pa, benchmarks_erie,
            benchmarks_counties, transit_stats, zcta_data,
            cdc_places, food_atlas, demographics,
            cdc_places_zcta, zcta_poi_stats)


@st.cache_data
def load_transit_shapes():
    shapes = pd.read_csv("data/raw/emta_shapes.csv")
    stops = pd.read_csv("data/raw/emta_stops.csv")
    return shapes, stops


@st.cache_data
def load_poi_data():
    pois = pd.read_csv("data/raw/erie_pois.csv")
    if "snap_eligible" not in pois.columns:
        pois["snap_eligible"] = pois["geocode_source"] == "usda_snap"
    else:
        pois["snap_eligible"] = pois["snap_eligible"].astype(str).str.lower() == "true"
    poi_stats = pd.read_csv("data/processed/tract_poi_stats.csv", dtype={"TRACTCE": str})
    poi_stats["TRACTCE"] = poi_stats["TRACTCE"].str.zfill(6)
    return pois, poi_stats


@st.cache_data
def load_boundaries():
    from pathlib import Path as _Path
    _root = _Path(__file__).resolve().parent.parent
    tracts = gpd.read_parquet(_root / "data/raw/boundaries_tracts.parquet")
    counties = gpd.read_parquet(_root / "data/raw/boundaries_counties.parquet")
    zctas = gpd.read_parquet(_root / "data/raw/boundaries_zctas.parquet")
    return tracts, counties, zctas


@st.cache_data
def load_stratification_data():
    df = pd.read_csv("data/processed/income_stratification.csv")
    return df


@st.cache_data
def load_pantry_data():
    monthly = pd.read_csv("data/processed/pantry_agency_monthly.csv", parse_dates=["date"])
    index = pd.read_csv("data/processed/pantry_agency_index.csv")
    return monthly, index


@st.cache_data
def build_merged_tract(
    year,
    _gdf_tracts, _census, _sh_data, _transit_stats,
    _cdc_places, _food_atlas, _demographics
):
    from lib.constants import COUNTY_FIPS, COUNTY_NAMES
    df_year = _census[_census["year"] == year].copy()
    sh_year = _sh_data[_sh_data["year"] == min(year, 2023)].copy()

    merged = _gdf_tracts.merge(df_year, left_on="TRACTCE", right_on="tract_code", how="left")
    merged = merged.merge(
        sh_year[["tract_code", "food_insecurity_rate", "unemployment_rate",
                 "disability_rate", "homeownership_rate"]],
        left_on="TRACTCE", right_on="tract_code", how="left"
    )
    merged = merged.merge(_transit_stats, on="TRACTCE", how="left")

    cdc_prep = _cdc_places.copy()
    cdc_prep["TRACTCE"] = cdc_prep["tract_code"]
    cdc_drop = [c for c in ["tract_code", "county_fips", "countyname", "year", "tract_geoid"] if c in cdc_prep.columns]
    merged = merged.merge(
        cdc_prep.drop(columns=cdc_drop), on="TRACTCE", how="left", suffixes=("", "_cdc")
    )
    merged = merged[[c for c in merged.columns if not c.endswith("_cdc")]]

    atlas_cols = ["tract_code", "food_desert_1_10", "food_desert_half_10",
                  "food_desert_vehicle", "low_income_tract", "low_access_pop",
                  "low_access_low_income_pop", "atlas_poverty_rate", "urban_tract"]
    atlas_cols = [c for c in atlas_cols if c in _food_atlas.columns]
    merged = merged.merge(
        _food_atlas[atlas_cols], left_on="TRACTCE", right_on="tract_code", how="left",
        suffixes=("", "_atlas")
    ).drop(columns=["tract_code_atlas", "tract_code"], errors="ignore")

    demo_year = _demographics[_demographics["year"] == year].copy()
    demo_keep = ["total_population", "median_age", "pct_white_non_hispanic",
                 "pct_black", "pct_hispanic", "pct_asian", "pct_other"]
    demo_keep = [c for c in demo_keep if c in demo_year.columns]
    demo_year["TRACTCE"] = demo_year["tract_code"]
    merged = merged.merge(demo_year[["TRACTCE"] + demo_keep], on="TRACTCE", how="left")

    merged["display_name"] = merged["NAMELSAD"]
    return merged


@st.cache_data
def build_merged_zcta(year, _gdf_zctas, _zcta_data, _cdc_places_zcta, _zcta_poi_stats):
    zcta_year = _zcta_data[_zcta_data["year"] == year].copy()
    merged = _gdf_zctas.merge(zcta_year, left_on="ZCTA5CE20", right_on="zcta", how="left")

    if len(_cdc_places_zcta.columns) > 1:
        merged = merged.merge(
            _cdc_places_zcta, left_on="ZCTA5CE20", right_on="zcta", how="left", suffixes=("", "_cdc")
        ).drop(columns=["zcta"] + [c for c in merged.columns if c.endswith("_cdc")], errors="ignore")

    if len(_zcta_poi_stats.columns) > 1:
        merged = merged.merge(_zcta_poi_stats, on="ZCTA5CE20", how="left")

    _county_short = merged["county_name"].fillna("").astype(str).str.replace(" County", "", regex=False).str.strip()
    _zip_col = merged["ZCTA5CE20"].astype(str)
    _name = merged["area_name"].astype(str).where(
        merged["area_name"].astype(str) != _zip_col, _county_short
    ).fillna(_county_short)
    merged["display_name"] = _name + " (" + _zip_col + ")"
    return merged


@st.cache_data
def build_merged_county(year, _gdf_counties, _benchmarks_counties):
    from lib.constants import COUNTY_FIPS, COUNTY_NAMES
    county_data = _benchmarks_counties[
        (_benchmarks_counties["year"] == year) &
        (_benchmarks_counties["name"].isin(COUNTY_NAMES))
    ].copy()
    county_data["COUNTYFP"] = county_data["name"].map(COUNTY_FIPS)
    merged = _gdf_counties.merge(county_data, on="COUNTYFP", how="left")
    merged["display_name"] = merged["NAME"]
    return merged
